version: 2

run:
  go: '1.21'
  timeout: 5m
  tests: true
  skip-dirs:
    - vendor/
    - third_party/

linters:
  disable-all: true
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - gocyclo
    - gosec
    - revive
    - gocritic
    - gocognit
    - goconst
    - goprintffuncname

linters-settings:
  gocyclo:
    min-complexity: 15
  goconst:
    min-len: 2
    min-occurrences: 2

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  sort-results: true 