name: Create Backmerge PR

on:
  push:
    branches:
      - main

jobs:
  create-backmerge-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: develop

      - name: Configure Git
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Check existing PR
        id: check-pr
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          # Проверяем существующий PR через GitHub API
          PR_DATA=$(curl -s -H "Authorization: token ${{ github.token }}" \
            "https://api.github.com/repos/${{ github.repository }}/pulls?head=${{ github.repository_owner }}:backmerge/main-to-develop&state=open")
          
          PR_NUMBER=$(echo "$PR_DATA" | jq -r '.[0].number // empty')
          if [ ! -z "$PR_NUMBER" ]; then
            echo "existing_pr=$PR_NUMBER" >> $GITHUB_OUTPUT
            echo "✅ Найден существующий PR #$PR_NUMBER"
          else
            echo "existing_pr=0" >> $GITHUB_OUTPUT
            echo "✅ Существующий PR не найден"
          fi

      - name: Close existing PR
        if: steps.check-pr.outputs.existing_pr != '0'
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          # Закрываем существующий PR через GitHub API
          curl -X PATCH \
            -H "Authorization: token ${{ github.token }}" \
            -H "Accept: application/vnd.github.v3+json" \
            -d '{"state":"closed"}' \
            "https://api.github.com/repos/${{ github.repository }}/pulls/${{ steps.check-pr.outputs.existing_pr }}"
          
          # Удаляем ветку через GitHub API
          curl -X DELETE \
            -H "Authorization: token ${{ github.token }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ github.repository }}/git/refs/heads/backmerge/main-to-develop"
          
          echo "✅ Закрыт PR #${{ steps.check-pr.outputs.existing_pr }} и удалена ветка"

      - name: Create backmerge branch
        run: |
          # Обновляем локальные ветки
          git fetch origin main develop
          
          # Удаляем локальную ветку, если она существует
          git branch -D backmerge/main-to-develop || true
          
          # Создаем новую ветку из develop
          git checkout develop
          git pull origin develop
          git checkout -b backmerge/main-to-develop
          
          # Мержим main в develop
          git merge origin/main --no-ff -m "Merge main into develop"
          
          # Форсированно пушим ветку
          git push origin backmerge/main-to-develop --force

      - name: Get commits to merge
        id: get-commits
        run: |
          git fetch origin main develop
          COMMITS=$(git log --pretty=format:"- %s" origin/develop..origin/main)
          echo "COMMITS<<EOF" >> $GITHUB_OUTPUT
          echo "$COMMITS" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Create Pull Request
        id: create-pr
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh pr create \
            --title "Backmerge: main → develop" \
            --body "Автоматический бэкмерж main в develop \

            Создано через GitHub Actions \

            ## Коммиты для слияния: \

            ${{ steps.get-commits.outputs.COMMITS }} \

            ## Метки: \

            - backmerge \

            - automated" \
            --base develop \
            --head backmerge/main-to-develop \
            --label "backmerge,automated" \
            --assignee "${{ github.actor }}"
          
          PR_URL=$(gh pr view --json url -q .url)
          echo "PR_URL=$PR_URL" >> $GITHUB_OUTPUT

      - name: Notify Telegram
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TG_CHAT }}
          token: ${{ secrets.TG_KEY }}
          message: |
            🔄 Создан PR для бэкмержа main в develop
            
            Ссылка на PR: ${{ steps.create-pr.outputs.PR_URL }}
            
            Ожидайте завершения проверки PR...

      - name: Notify Error to Telegram
        if: failure()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TG_CHAT }}
          token: ${{ secrets.TG_KEY }}
          message: |
            ❌ Ошибка при создании бэкмержа
            
            Не удалось создать Pull Request из main в develop
            
            Ссылка на коммит: ${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}
            Ссылка на зафейленный экшн: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
            
            Пожалуйста, проверьте логи и исправьте ошибку. 
