name: Develop Build

on:
  push:
    branches: [ develop ]
    paths:
      - 'app/**'
      - 'gradle/**'
      - 'build.gradle*'
      - 'settings.gradle*'
      - 'gradle.properties'
      - '.github/workflows/develop.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    env:
      TRACER_APP_TOKEN: ${{ secrets.TRACER_APP_TOKEN }}
      TRACER_PLUGIN_TOKEN: ${{ secrets.TRACER_PLUGIN_TOKEN }}
      APP_METRICA_API_KEY: ${{ secrets.APP_METRICA_API_KEY }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    # Сохраняем время начала сборки
    - name: Set build start time
      id: build-time-start
      run: echo "BUILD_START=$(date +%s)" >> $GITHUB_OUTPUT
    
    - name: Generate build number
      id: buildnumber
      uses: onyxmueller/build-tag-number@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        prefix: 'android'
    
    # Получаем список коммитов для ченджлога
    - name: Get changelog
      id: changelog
      run: |
        # Получаем последний тег develop
        git fetch --tags
        LATEST_TAG=$(git tag -l 'develop-*' --sort=-v:refname | head -n 1 || echo "")
        
        if [ -z "$LATEST_TAG" ]; then
          # Если тегов нет, берем последние 10 коммитов
          COMMITS=$(git log -n 10 --pretty=format:"- %s (%h)" --reverse)
        else
          # Если есть тег, берем коммиты после него
          COMMITS=$(git log ${LATEST_TAG}..HEAD --pretty=format:"- %s (%h)" --reverse)
        fi
        
        # Сохраняем список коммитов
        echo "COMMITS<<EOF" >> $GITHUB_OUTPUT
        echo "$COMMITS" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
    
    # Установка Android SDK Build Tools
    - name: Setup Android SDK
      uses: android-actions/setup-android@v2
      with:
        cmdline-tools-version: '8.0'
        packages: 'build-tools;35.0.0,build-tools;33.0.0,build-tools;30.0.3,build-tools;29.0.3,platforms;android-35'

    # Кэширование Gradle Wrapper
    - name: Cache Gradle Wrapper
      id: cache-gradle-wrapper
      continue-on-error: true
      timeout-minutes: 5
      uses: actions/cache@v3
      with:
        path: ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-wrapper-
    
    # Кэширование зависимостей Gradle
    - name: Cache Gradle dependencies
      id: cache-gradle-deps
      continue-on-error: true
      timeout-minutes: 10
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/daemon
          ~/.gradle/native
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    
    # Кэширование Maven репозитория
    - name: Cache Maven repository
      id: cache-maven
      continue-on-error: true
      timeout-minutes: 8
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/build.gradle*') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    
    # Кэширование Android SDK
    - name: Cache Android SDK
      id: cache-android-sdk
      continue-on-error: true
      timeout-minutes: 15
      uses: actions/cache@v3
      with:
        path: |
          ${{ env.ANDROID_HOME }}
          ~/.android/cache
        key: ${{ runner.os }}-android-sdk-${{ hashFiles('**/build.gradle*') }}
        restore-keys: |
          ${{ runner.os }}-android-sdk-
    
    # Кэширование результатов сборки
    - name: Cache Build results
      id: cache-build
      continue-on-error: true
      timeout-minutes: 12
      uses: actions/cache@v3
      with:
        path: app/build
        key: ${{ runner.os }}-app-build-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-app-build-
    
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    
    - name: Determine develop version
      id: version
      run: |
        # Получаем последний тег релиза
        git fetch --tags
        LATEST_TAG=$(git tag -l 'v*' --sort=-v:refname | head -n 1 || echo "v1.0.0")
        
        # Если тега нет, начинаем с версии 1.0.0
        if [ -z "$LATEST_TAG" ]; then
          LATEST_TAG="v1.0.0"
        fi
        
        # Удаляем префикс v из тега
        LATEST_VERSION="${LATEST_TAG#v}"
        
        # Для develop ветки используем текущую версию с суффиксом develop.X
        DEVELOP_VERSION="${LATEST_VERSION}-develop.${{ steps.buildnumber.outputs.build_number }}"
        echo "Develop версия: $DEVELOP_VERSION"
        
        # Выводим для использования в других шагах
        echo "DEVELOP_VERSION=$DEVELOP_VERSION" >> $GITHUB_OUTPUT
    
    - name: Update version code and name
      run: |
        echo "Build number: ${{ steps.buildnumber.outputs.build_number }}"
        echo "Develop Version: ${{ steps.version.outputs.DEVELOP_VERSION }}"
        
        # Обновляем версию в build.gradle.kts - для develop добавляем суффикс с номером билда
        sed -i "s/versionCode = .*/versionCode = ${{ steps.buildnumber.outputs.build_number }}/g" app/build.gradle.kts
        sed -i "s/versionName = .*/versionName = \"${{ steps.version.outputs.DEVELOP_VERSION }}\"/g" app/build.gradle.kts
    
    # Запускаем unit-тесты с оптимизациями
    - name: Run unit tests
      run: ./gradlew testDebugUnitTest --build-cache --parallel --no-daemon
      
    # Публикуем результаты тестов
    - name: Publish Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        files: '**/build/test-results/**/*.xml'
    
    # Собираем debug-версию с оптимизациями
    - name: Build debug APK
      run: ./gradlew assembleDebug --build-cache --parallel --no-daemon

    # Собираем release-версию с оптимизациями
    - name: Build release APK
      run: ./gradlew assembleRelease --build-cache --parallel --no-daemon
    
    # Подписываем релизные APK файлы
    - name: Sign Release APK
      id: sign_apk
      uses: r0adkll/sign-android-release@v1
      env:
        BUILD_TOOLS_VERSION: "35.0.0"
        ANDROID_HOME: "/usr/local/lib/android/sdk" # Явно задаем путь к Android SDK
      with:
        releaseDirectory: app/build/outputs/apk/release
        signingKeyBase64: ${{ secrets.RELEASE_KEYSTORE_BASE64 }}
        alias: ${{ secrets.KEY_ALIAS }}
        keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
        keyPassword: ${{ secrets.KEY_PASSWORD }}

    # Переименовываем APK файлы, добавляя номер версии
    - name: Rename APK files
      run: |
        mkdir -p renamed_apk
        
        # Копируем debug APK
        cp app/build/outputs/apk/debug/app-debug.apk renamed_apk/app-debug-${{ steps.version.outputs.DEVELOP_VERSION }}.apk
        echo "✅ Debug APK file copied successfully"
        
        # Копируем подписанный release APK с проверкой
        if [ -f "${{ steps.sign_apk.outputs.signedReleaseFile }}" ]; then
          cp "${{ steps.sign_apk.outputs.signedReleaseFile }}" "renamed_apk/app-release-${{ steps.version.outputs.DEVELOP_VERSION }}.apk"
          echo "✅ Release APK file copied successfully"
        else
          echo "⚠️ Signed Release APK not found at: ${{ steps.sign_apk.outputs.signedReleaseFile }}"
          echo "Looking for alternative APK file..."
          # Поиск альтернативных файлов
          if [ -f "app/build/outputs/apk/release/app-release-signed.apk" ]; then
            cp "app/build/outputs/apk/release/app-release-signed.apk" "renamed_apk/app-release-${{ steps.version.outputs.DEVELOP_VERSION }}.apk"
            echo "✅ Alternative Release APK file copied"
          else
            echo "❌ No signed Release APK found!"
            exit 1
          fi
        fi
    
    # Загружаем debug APK
    - name: Upload Debug APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug-${{ steps.version.outputs.DEVELOP_VERSION }}
        path: renamed_apk/app-debug-${{ steps.version.outputs.DEVELOP_VERSION }}.apk
        retention-days: 30
        if-no-files-found: error
        overwrite: true
        compression-level: 0
        content-type: application/vnd.android.package-archive
    
    # Загружаем release APK
    - name: Upload Release APK
      uses: actions/upload-artifact@v4
      with:
        name: app-release-${{ steps.version.outputs.DEVELOP_VERSION }}
        path: renamed_apk/app-release-${{ steps.version.outputs.DEVELOP_VERSION }}.apk
        retention-days: 30
        if-no-files-found: error
        overwrite: true
        compression-level: 0
        content-type: application/vnd.android.package-archive
    
    # Расчет времени сборки
    - name: Calculate build time
      id: build-time
      run: |
        END_TIME=$(date +%s)
        START_TIME=${{ steps.build-time-start.outputs.BUILD_START }}
        DURATION=$((END_TIME - START_TIME))
        
        # Форматируем время в минуты и секунды
        MINUTES=$((DURATION / 60))
        SECONDS=$((DURATION % 60))
        
        if [ $MINUTES -gt 0 ]; then
          BUILD_TIME="${MINUTES}м ${SECONDS}с"
        else
          BUILD_TIME="${SECONDS}с"
        fi
        
        echo "build_time=$BUILD_TIME" >> $GITHUB_OUTPUT
    
    # Создаем релиз с переименованными APK
    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "renamed_apk/app-debug-${{ steps.version.outputs.DEVELOP_VERSION }}.apk,renamed_apk/app-release-${{ steps.version.outputs.DEVELOP_VERSION }}.apk"
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: develop-${{ steps.buildnumber.outputs.build_number }}
        name: Develop Build ${{ steps.version.outputs.DEVELOP_VERSION }}
        body: |
          Автоматическая сборка из ветки develop
          
          Номер сборки: ${{ steps.buildnumber.outputs.build_number }}
          Версия: ${{ steps.version.outputs.DEVELOP_VERSION }}
          Коммит: ${{ github.sha }}
          
          ## Последние изменения:
          ${{ steps.changelog.outputs.COMMITS }}
          
          ## Артефакты:
          - Debug APK для тестирования
          - Release APK с подписью для расширенного тестирования
          
          Время сборки: ${{ steps.build-time.outputs.build_time }}
        draft: false
        prerelease: true
        makeLatest: false
    
    # Очистка кэшей в редких случаях
    - name: Cleanup Gradle Cache
      # Запускается только по условию, например, еженедельно
      if: github.event_name == 'schedule' && github.event.schedule == '0 0 * * 0'
      run: |
        rm -rf ~/.gradle/caches/modules-2/modules-2.lock
        rm -rf ~/.gradle/caches/transforms-1
        rm -rf ~/.gradle/caches/journal-1
        rm -rf ~/.gradle/caches/jars-3 
